language: node_js
node_js: 
  - 'node'
cache: 
  npm: true
  directories:
    - public
    - .cache
script:
  - CI='' npm run build
deploy:
  provider: pages
  cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on: 
    branch: main    